[package]
name = "thirty-days-of-rust"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "day1"
path = "src/bin/day1.rs"

[[bin]]
name = "work1"
path = "src/bin/work1.rs"

[[bin]]
name = "day3"
path = "src/bin/day3.rs"

[[bin]]
name = "calculator"
path = "src/bin/calculator.rs"

[[bin]]
name = "day4"
path = "src/bin/day4.rs"

[[bin]]
name = "day6"
path = "src/bin/day6.rs"

[[bin]]
name = "work6"
path = "src/bin/work6.rs"

[[bin]]
name = "day7"
path = "src/bin/day7.rs"

[[bin]]
name = "work7"
path = "src/bin/work7.rs"

[dependencies]
