[package]
name = "thirty-days-of-rust"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "work1"
path = "src/work1.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"

[[bin]]
name = "calculator"
path = "src/calculator.rs"

[[bin]]
name = "day4"
path = "src/day4.rs"

[dependencies]
